<?php
    $this->headMeta()
      ->appendName('description', $this->translate('A demonstration application for the Zend 2 framework'));
?>

<div class="col-xs-12 col-md-6">

<h1>Introduction</h1>

<p>This is the home page of this ZF2 demo application. It demonstrates the use
    of login/logout, access control and some usage of Bootstrap CSS.</p>
<p>The source code is available
    <a href="https://github.com/JVerstry/Zend-2-Login-Access-Control-Demo">here</a>.</p>

<p>Three users have been created:</p>

<ul>
    <li><strong>user1</strong> with password <em>user1</em>, having its own <a href="/restricted/user/user1">user1</a> page</li>
    <li><strong>user2</strong> with password <em>user2</em>, having its own <a href="/restricted/user/user2">user2</a> page</li>
    <li><strong>admin</strong> with password <em>admin</em>, having its own <a href="/restricted/admin">admin</a> page</li>
</ul>
</div>

<div class="col-xs-12 col-md-6">
    
<?php echo $this->loginWidget(); ?>
    
</div>

