
<div class="col-xs-12 col-md-6">

<h1>Clients</h1>

<?php
if ( sizeof($this->clients) > 0 ) {
    foreach($this->clients as $client)
    {
        echo '<a href="/client/'.$client->getId().'">'.$client->getName().'</a><br />';
    }
} else {
    echo '<p>No clients.</p>';
}
?>
<br />
<a href="/resetWithDemoData" class="btn btn-default">Reset With Demo Data</a>

</div>

<div class="col-xs-12 col-md-6">

    <h1>Remark</h1>
    
    <p>Click on a client to display it orders.</p>

</div>

