
<div class="col-xs-12 col-md-6">

<h1>Clients</h1>

<?php
if ( sizeof($this->clients) > 0 ) {
    
    echo '<table class="table table-nonfluid">';
    echo '<thead><tr>';
    echo '<th>Name</th>';
    echo '<th>Delete</th>';
    echo '</tr></thead>';
    echo '<tbody>';
    
    foreach($this->clients as $client)
    {
        echo '<tr><td>'
             .'<a href="/client/'.$client->getId().'">'.$client->getName().'</a>&nbsp;&nbsp;&nbsp;'
             .'</td><td><a href="/deleteClient/'.$client->getId().'">Delete</a>'
             .'</td></tr>';
    }
    
    echo '</tbody>';
    echo '</table>';
    
} else {
    echo '<p>No clients.</p>';
}

echo '<p><a href="/createClient">Add Client</a></p>';


?>
<br />
<a href="/resetWithDemoData" class="btn btn-default">Reset With Demo Data</a>

</div>

<div class="col-xs-12 col-md-6">

    <h1>Remark</h1>
    
    <p>Click on a client to display its orders.</p>

</div>

