
<div class="col-xs-12 col-md-6">

<h1>Orders Of <?php $this->client->getName(); ?></h1>

<?php
echo '<br />';
$orders = $this->client->getOrders();
if ( sizeof($orders) > 0 ) {
    foreach($orders as $order)
    {
        echo '<a href="/order/'.$order->getId().'">Order '.$order->getId().'</a><br />';
    }
} else {
    echo '<p>No orders.</p>';
}
?>


</div>

<div class="col-xs-12 col-md-6">

    <p>Click on an order to display its details.</p>
    
</div>

